/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;


public class App {


    public String getGreeting() {
        return "Hello World!";
    }

    public static void imageIoWrite() {

    }


    public static void main(String[] args) throws IOException {

        String fileN = "app/src/main/resources/image.bmp";
        BufferedImage img = ImageIO.read(new File(fileN));
        bitmap obj = new bitmap(img,"app/src/main/resources/image5.bmp");
//        if(args[2].equals("BlacknWhite") ){
            obj.BlacknWhite();
//            else if(args[2].equals("BlacknWhite") )
              obj.light();
              obj.dark();





    }
}





